version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily

  # find . -name go.mod | sort | sed 's/^\.\(.*\)\/go.mod$/  - package-ecosystem: gomod\n    directory: "\1"\n    schedule:\n      interval: daily/'
  - package-ecosystem: gomod
    directory: "/awsenv"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/basicauth"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/clock"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/extraio"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/flaky"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/httpclient"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/httpdebug"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/jsonlazy"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/maininfo"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/names"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/pgtxtar"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/process"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/syncx"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/task"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/zaplog"
    schedule:
      interval: daily
